<%
drb_opts = "--drb --port 8991"
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun} #{drb_opts}"
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} --strict --tags ~@wip --tags ~@print #{drb_opts}"
%>

default: <%= std_opts %> --color features <%= drb_opts %>
wip: --tags @wip:3 --wip features
rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip --tags ~@print
autotest: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip --tags ~@print
autotest-all: <%= std_opts %> --color features
